Repository FromDoppler/emms24, pull requests merged in 2024-11, with the labels that each got.

#147 DS-5376 fix dt backgorund
  src/1.0.0/css/pages/ecommerce.css
Labels: size/XS

#148 DS-5379_add_autocomplete_user_form
  components/digital-trends/pre/register-form.php
  src/1.0.0/js/autoCompleteUserForm.js
Labels: size/M

#149 DS-5381_add_validation_in_dt_form
  src/1.0.0/js/homeDigital.js
Labels: size/M

#150 DS-5377 show sponsors list component
  components/sponsorsList.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
Labels: size/S

#151 DS-5377 refactor sponsor list component
  components/sponsorsList.php
  utils/DB.php
Labels: size/M

#152 DS-5382 update code video
  components/digital-trends/pre/digital-trends/video-ticketing.php
Labels: size/XS

#153 DS-5378 active promotion code param
  components/digital-trends/pre/checkout/checkout.php
Labels: size/M

#154 DS-5379 autocomplete form
  src/1.0.0/js/autoCompleteUserForm.js
Labels: size/M

#155 DS-5392 change pricing style
  components/digital-trends/pre/digital-trends/entry-plans.php
  components/digital-trends/pre/digital-trends/vip-features.php
  src/1.0.0/css/components/features.css
  src/1.0.0/css/components/prices-plans.css
Labels: size/M

#156 DS 5389 date counter component
  components/date-counter.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  pages/digital-trends/pre/home-registrado.php
  pages/digital-trends/pre/home.php
  src/1.0.0/css/components/date-counter.css
  src/1.0.0/js/dateCounter.js
  src/components/date-counter.php
Labels: size/L

#157 DS-5384 spreadsheet vip column price
  stripe/controllers/StripeCustomersController.php
  utils/SpreadSheetGoogle.php
Labels: size/M

#159 DS-5399 speark card composition pattern
  components/SpeakerCard.php
  components/SpeakerCardComponent/CompanyFooter.php
  components/SpeakerCardComponent/CompanyLogo.php
  components/SpeakerCardComponent/Description.php
  components/SpeakerCardComponent/Label.php
  components/SpeakerCardComponent/SocialLinks.php
  components/SpeakerCardComponent/SpeakerBio.php
  components/SpeakerCardComponent/SpeakerInfo.php
  components/digital-trends/schedule/showSpeakersByDay.php
Labels: size/L

#160 DS-5399 fix speaker card
  components/SpeakerCard.php
  components/SpeakerCardComponent/CompanyLogo.php
  components/digital-trends/schedule/showSpeakersByDay.php
Labels: size/M

#161 DS-5398 add interview type
  components/SpeakerCardComponent/CompanyFooter.php
  components/SpeakerCardComponent/Label.php
  components/SpeakerCardComponent/SpeakerBio.php
  components/SpeakerCardComponent/SpeakerInfo.php
  components/digital-trends/schedule/showSpeakersByDay.php
  src/1.0.0/css/components/calendar.css
Labels: size/M

#162 DS-5400 change sponsor interna
  sponsors-interna.php
Labels: size/M

#164 DS-5402 remove validations without form
  src/1.0.0/js/homeDigital.js
Labels: size/XS

#163 DS-5401 add day3 hour
  components/digital-trends/schedule/showSpeakersByDay.php
Labels: size/XS

#165 DS-5404 init stage during
  pages/digital-trends/during/checkout-success.php
  pages/digital-trends/during/checkout.php
  pages/digital-trends/during/digital-trends-registrado.php
  pages/digital-trends/during/digital-trends.php
  pages/digital-trends/during/home-registrado.php
  pages/digital-trends/during/home.php
Labels: size/L

#166 DS-5396 add sponsor list in sponsor
  sponsors-promo.php
Labels: size/M

#167 DS-5405 sponsorsList on resourcesLibrary Page
  sponsors-registrado.php
  sponsors.php
Labels: size/XS

#169 DS-5407 change module content
  components/digital-trends/during/central-video.php
  pages/digital-trends/during/home-registrado.php
  pages/digital-trends/during/home.php
Labels: size/M

#170 DS-5408 during faq
  components/digital-trends/during/faqs.php
  pages/digital-trends/during/home-registrado.php
  pages/digital-trends/during/home.php
Labels: size/M

#171 DS-5411 hello bar during transition
  components/hello-bar.php
  pages/digital-trends/during/digital-trends.php
  pages/digital-trends/during/home-registrado.php
  pages/digital-trends/during/home.php
  src/1.0.0/css/components/hellobar.css
Labels: size/L

#173 DS-5406 hello module during
  components/digital-trends/during/home/hello-module.php
Labels: size/L

#175 DS-5394 event live component
  components/digital-trends/during/digital-trends/event-live.php
  config.php
Labels: size/M

#176 DS-5416 smart schedulle buttons
  components/digital-trends/schedule/schedule.php
  components/digital-trends/schedule/speakers.php
  src/1.0.0/css/components/calendar.css
Labels: size/L

#177 DS-5416 schedulle button content
  components/digital-trends/schedule/schedule.php
Labels: size/S

#178 DS-5418 dt page structure
  components/sponsorsList.php
  pages/digital-trends/during/digital-trends.php
Labels: size/XS

#179 DS-5419 sponsors hellobar
  components/hello-bar.php
  sponsors.php
Labels: size/XS

#181 DS-5393 buttons live in speaker card
  components/SpeakerCardComponent/Description.php
  components/SpeakerCardComponent/DescriptionButton.php
  components/digital-trends/schedule/mobile-carousel.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/general/constants.css
Labels: size/L

#183 DS-5411 fix hello bar
  components/hello-bar.php
Labels: size/XS

#184 DS-5416_fix_schedule
  components/digital-trends/schedule/speakers.php
Labels: size/L

#185 DS-5421 dt register modules
  components/digital-trends/during/digital-trends/event-live.php
  pages/digital-trends/during/digital-trends-registrado.php
  src/1.0.0/css/components/hero-conference.css
Labels: size/M

#186 DS-5411 fix hellobar
  components/hello-bar.php
Labels: size/S

#188 DS-5422-feedback-qa-during
  components/SpeakerCardComponent/DescriptionButton.php
  components/digital-trends/during/digital-trends/certificate/certificate.php
  components/digital-trends/during/digital-trends/event-live.php
  components/digital-trends/during/home/hello-module.php
  components/digital-trends/schedule/schedule.php
  components/digital-trends/schedule/showSpeakersByDay.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/certificate-modal.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/hero-conference.css
  src/1.0.0/css/components/newCalendar.css
  src/1.0.0/css/components/prices-plans.css
Labels: size/XL

#189 DS-5425 transition stage
  components/digital-trends/during/digital-trends/event-live.php
  src/img/placas/migrate-twitch.png
  src/img/placas/technical-error.png
  src/img/placas/transition-1.png
  src/img/placas/transition-2.png
  src/img/placas/transition-3.png
Labels: size/XS

#191 DS-5423 transition dt
  components/digital-trends/during/digital-trends/event-live.php
  components/digital-trends/during/register-form.php
  components/digital-trends/schedule/showSpeakersByDay.php
  config.php
  src/1.0.0/css/components/hero-conference.css
Labels: size/M

#193 DS-5427 handle vip emails stripe
  stripe/controllers/StripeCustomersController.php
Labels: size/M

#194 DS-5428 share content
  components/digital-trends/during/digital-trends/head.php
  components/digital-trends/during/home/head.php
  components/share.php
  pages/digital-trends/during/digital-trends-registrado.php
  pages/digital-trends/during/digital-trends.php
  pages/digital-trends/during/home-registrado.php
  pages/digital-trends/during/home.php
  src/1.0.0/css/components/calendar.css
Labels: size/L

#195 DS-5429 delete bullets
  components/digital-trends/pre/checkout/checkout-success.php
Labels: size/XS

#196 DS-5432 first home module post
  components/digital-trends/post/home/hello-module.php
  pages/digital-trends/post/home-registrado.php
  pages/digital-trends/post/home.php
  src/1.0.0/css/components/event-cards.css
  src/img/card-image-digitaltrends-post.png
Labels: size/L

#199 DS-5435 change intell input
  src/components/intellInput.php
Labels: size/XS

#198 DS-5434 add transition vip block
  components/digital-trends/during/digital-trends/event-live.php
  src/1.0.0/css/components/hero-conference.css
Labels: size/M

#200 DS-5436 central video post
  components/digital-trends/post/central-video.php
  pages/digital-trends/post/home-registrado.php
  pages/digital-trends/post/home.php
  src/1.0.0/css/components/hero-conference.css
Labels: size/M

#201 DS-5412 live workshop link
  components/digital-trends/during/digital-trends/event-live.php
Labels: size/XS

#202 DS-5437 speaker carousel post
  components/digital-trends/post/speakers-carousel.php
  pages/digital-trends/post/home-registrado.php
  pages/digital-trends/post/home.php
  src/1.0.0/css/components/speakers-list.css
Labels: size/L

#203 DS-5438 dt post form module
  components/digital-trends/post/register-form.php
  components/digital-trends/post/register-withoutform.php
  pages/digital-trends/post/digital-trends.php
  src/1.0.0/css/pages/ecommerce.css
Labels: size/L

#204 DS-5442-schedule-post
  components/digital-trends/schedule/schedule.php
  components/digital-trends/schedule/speakers.php
Labels: size/S

#205 DS-5443 buttos post logic
  components/SpeakerCardComponent/DescriptionButton.php
  src/1.0.0/css/components/calendar.css
Labels: size/S

#206 DS-5439 digital trends egistered hello module
  components/digital-trends/post/digital-trends/hello-module.php
  components/digital-trends/post/digital-trends/hello-vip-module.php
  pages/digital-trends/post/digital-trends-registrado.php
  src/1.0.0/css/components/hero-registration.css
Labels: size/M

#208 DS-5447 add new capsule
  sponsors-registrado.php
  sponsors.php
  src/img/conferences24/logos/juan-manuel-emprende-logo.png
  src/img/conferences24/portada-capsula-juanmanuel-card-min.png
Labels: size/S

#207 DS-5446 vip feature post module
  components/digital-trends/post/digital-trends/vip-features.php
  pages/digital-trends/post/digital-trends-registrado.php
  src/1.0.0/css/components/features.css
Labels: size/M

#209 DS-5446 new video ticketing module
  components/digital-trends/post/digital-trends/video-ticketing.php
  pages/digital-trends/post/digital-trends-registrado.php
  src/1.0.0/css/components/central-video.css
  src/img/vip-image-module.png
Labels: size/S

#210 DS-5448 speaker interna page & components
  components/digital-trends/post/speaker-interna/event-recorded.php
  components/digital-trends/post/speaker-interna/promo-vip.php
  pages/digital-trends/post/speaker-interna.php
  speaker-interna.php
Labels: size/L

#211 DS-5431 move-module
  pages/digital-trends/post/digital-trends-registrado.php
Labels: size/XS

#212 DS-5448 speaker interna fix styles
  components/digital-trends/post/speaker-interna/event-recorded.php
  components/digital-trends/post/speaker-interna/promo-vip.php
  pages/digital-trends/post/digital-trends-registrado.php
  src/1.0.0/css/components/features.css
Labels: size/M

#214 DS-5450 feedback post
  components/SpeakerCardComponent/Description.php
  components/SpeakerCardComponent/DescriptionButton.php
  components/digital-trends/post/digital-trends/head.php
  components/digital-trends/post/home/head.php
  components/digital-trends/pre/event-numbers.php
  components/digital-trends/schedule/schedule.php
  components/digital-trends/schedule/showSpeakersByDay.php
  components/share.php
  pages/digital-trends/post/digital-trends-registrado.php
  pages/digital-trends/post/digital-trends.php
  pages/digital-trends/post/home-registrado.php
  pages/digital-trends/post/home.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/js/counterAnimation.js
  src/components/speakersPostRegistrado.php
Labels: size/M
