Repository FromDoppler/emms24, pull requests merged in 2024-04, with the labels that each got.

#39 DS-5081 add user vip to doppler list
  config.php
  stripe/controllers/StripeCustomersController.php
  stripe/models/SubscriberDopplerList.php
Labels: size/M

#40 DS-5066 spread user vip stripe
  .docker/docker-compose.yml
  config.php
  stripe/controllers/StripeCustomersController.php
  stripe/models/SubscriberDopplerList.php
  stripe/utils/SpreadSheetGoogle.php
Labels: size/M

#41 DS-5086_add_switch_form
  ediciones-anteriores.php
  speaker-interna.php
  sponsors.php
  src/1.0.0/css/components/form.css
  src/1.0.0/js/common/switchForm.js
  src/1.0.0/js/enums/eventsType.enum.js
  src/1.0.0/js/homeEcommerce.js
  src/1.0.0/js/previousEditions.js
  src/1.0.0/js/speakersInterna.js
  src/1.0.0/js/sponsors.js
  stages/ecommerce/pre/ecommerce.php
Labels: size/L

#42 DS-5088_update_script_path
  src/1.0.0/js/date.js
  stages/ecommerce/pre/ecommerce.php
Labels: size/L

#43 DS-5069_sponsors_new_pages
  services/register.php
  services/registerSponsor.php
  sponsor-promo.php
  sponsors-interna.php
  sponsors.php
  src/1.0.0/css/components/doppler-academy-banner.css
  src/1.0.0/css/components/register-modal.css
  src/1.0.0/css/pages/internal-sponsors.css
  src/1.0.0/css/pages/sponsor-promo.css
  src/1.0.0/css/pages/sponsors.css
  src/1.0.0/css/styles.css
  src/1.0.0/js/common/switchForm.js
  src/1.0.0/js/homeEcommerce.js
  src/1.0.0/js/sponsorPromo.js
  src/1.0.0/js/sponsors.js
  src/components/doppler-academy-banner.php
  src/img/bg-section-5.png
  src/img/emoji-book.svg
  src/img/imagetest.png
  src/img/rompecabez-asset.png
  src/img/sponsor-asset.png
  src/img/sponsor-promo.png
  src/img/sponsors-promo.svg
  src/img/tick-success.png
Labels: size/XXL

#44 DS-5089_feat_change_UI
  index.php
  registrado.php
  sponsors-registrado.php
  sponsors.php
  src/1.0.0/css/components/benefits-carousel.css
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/css/components/features.css
  src/1.0.0/css/components/form.css
  src/1.0.0/css/components/grid.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/css/pages/sponsors.css
  src/1.0.0/js/common/switchForm.js
  src/1.0.0/js/toggleVipElements.js
  src/components/companiesList.php
  src/components/speakers.php
  src/img/icons/separator-white.png
  src/img/imagetest.png
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/XXL

#46 DS-5083 DS-5085 checkout succes & faqs & edit speakers adm
  admin/speakers/edit_speakers.php
  checkout-success.php
  checkout.php
Labels: size/L

#48 DS-5093_hotfix_deploy
  index.php
  registrado.php
  sponsors-registrado.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/pages/internal-sponsors.css
  src/1.0.0/css/pages/sponsors.css
  src/1.0.0/js/common/switchForm.js
  src/img/imagetest2.png
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/M

#50 DS-5098 dplid users
  src/1.0.0/js/global.js
  src/1.0.0/js/user.js
Labels: size/S

#49 DS-5094_post_deplo_changes
  index.php
  sponsors-promo.php
  sponsors-registrado.php
  sponsors.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/features.css
  src/1.0.0/css/components/form.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/sponsors-promo.css
  src/1.0.0/css/pages/sponsors.css
  src/1.0.0/js/sponsorsPromo.js
  src/components/doppler-academy-banner.php
  src/components/speakers.php
  src/components/speakers__backup--ecommerce.php
  src/img/bg-section-5.png
  src/img/icons/icon-exclude.svg
  stages/ecommerce/pre/ecommerce-registrado.php
Labels: size/L

#51 feat: add new changes post deploy
  index.php
  src/1.0.0/css/components/benefits-carousel.css
  src/1.0.0/css/components/form.css
  src/1.0.0/css/components/prices-plans.css
  src/components/speakers.php
  src/img/benefits/beneficio-asesoria.png
  src/img/benefits/beneficio-coderhouse.png
  src/img/benefits/beneficio-coderhouse2.png
  src/img/benefits/beneficio-cursos.png
  src/img/benefits/beneficio-plantilla.png
  src/img/icons/icon-exclude.svg
  src/img/imagetest.png
  src/img/imagetest2.png
  stages/ecommerce/pre/ecommerce.php
Labels: size/S

#52 DS-5099 fix img sponsors
  src/components/companiesList.php
Labels: size/XS

#54 DS-5106 refactor stripe registration
  stripe/controllers/StripeCustomersController.php
Labels: size/S

#53 DS-5096 redirect if unregistered user
  checkout.php
Labels: size/S

#55 DS-5092_user_error_message
  src/1.0.0/css/components/form.css
  src/1.0.0/js/common/formsValidators.js
  src/1.0.0/js/common/switchForm.js
  src/img/benefits/Mask group.png
  stages/ecommerce/pre/ecommerce.php
Labels: size/M

#56 DS-5103 admin speakers debate
  admin/speakers/add_speakers.php
  admin/speakers/edit_speakers.php
Labels: size/XS

#57 DS-5102_debate
  src/1.0.0/css/components/calendar.css
  src/components/speakers.php
  src/img/icons/icon-debate.svg
Labels: size/L

#58 DS-5107_calendar_changes
  src/1.0.0/css/components/calendar.css
  src/components/speakers.php
Labels: size/M

#59 DS-5108_benefits_changes
  src/1.0.0/css/components/benefits-carousel.css
  src/img/benefits/Mask group.png
  src/img/benefits/beneficio-asesoria.png
  src/img/benefits/beneficio-coderhouse.png
  src/img/benefits/beneficio-coderhouse2.png
  src/img/benefits/beneficio-ebook.png
  src/img/benefits/beneficio-mochila.png
  src/img/benefits/beneficio-pack-mentoria.png
  src/img/benefits/beneficio-swann.png
  src/img/benefits/beneficios-curso-algoritmos.png
  stages/ecommerce/pre/ecommerce.php
Labels: size/M

#60 DS-5111_fix_texts_styles
  index.php
  registrado.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/features.css
  src/1.0.0/css/components/premium-content-banner.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/css/pages/sponsors-promo.css
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/M

#61 DS-5108_hidden_benefits
  src/1.0.0/js/mediaPartners.js
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/S

#62 DS-5113_new_email_flow
  utils/relay-templates/ecommerce/ecommerce-pre-template.html
  utils/relay-templates/ecommerce/old/ecommerce-pre-template.html
Labels: size/XXL

#63 DS-5114 during stage pages
  stages/ecommerce/during/ecommerce-registrado.php
  stages/ecommerce/during/ecommerce.php
Labels: size/XL

#64 DS-5109_DS-5110_certificate
  descarga-certificado.php
  src/1.0.0/js/certificate/certificateWorkshop.js
  src/1.0.0/js/common/certificate.js
  textify/certificate-emms2024.php
  textify/certificate-emms2024qa.php
Labels: size/L

#65 DS-5115_during_v1
  src/1.0.0/css/pages/ecommerce.css
  stages/ecommerce/during/ecommerce-registrado.php
  stages/ecommerce/during/ecommerce.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/L

#67 DS-5118 cache settings
  src/components/cacheSettings.php
Labels: size/XS

#66 DS-5117 post stage pages ecommerce
  stages/ecommerce/post/ecommerce-registrado.php
  stages/ecommerce/post/ecommerce.php
Labels: size/XXL
