Repository FromDoppler/emms24, pull requests merged in 2024-05, with the labels that each got.

#68 DS-5119 speakers change current event filter
  stages/ecommerce/post/ecommerce-registrado.php
  stages/ecommerce/post/ecommerce.php
Labels: size/S

#69 DS-5120 label input url youtube zoom
  admin/speakers/add_speakers.php
  admin/speakers/edit_speakers.php
  admin/speakers/view_speakers.php
Labels: size/XS

#72 DS-5121_final_desing
  src/1.0.0/js/certificate/certificateWorkshop.js
  src/components/speakers.php
  stages/ecommerce/during/ecommerce.php
Labels: size/S

#74 DS-5123_feedback_post_deplo
  index.php
  registrado.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/hero-conference.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/home.css
  src/components/companiesList.php
  src/components/speakers.php
  stages/ecommerce/during/ecommerce-registrado.php
  stages/ecommerce/during/ecommerce.php
Labels: size/L

#75 DS-5126_fixes
  src/1.0.0/css/components/hero-conference.css
  src/components/speakers.php
  stages/ecommerce/during/ecommerce.php
Labels: size/M

#77 DS-5131 update script datetime event country
  src/1.0.0/js/newDate.js
Labels: size/M

#76 DS-5129
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  index.php
  registrado.php
  speaker-interna.php
  sponsors-interna.php
  sponsors-promo.php
  sponsors-registrado.php
  src/1.0.0/css/components/benefits-carousel.css
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/hero-conference.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/js/certificate/certificateSpeaker.js
  src/components/head-home.php
  src/components/speakers.php
  src/components/speakersPost.php
  src/components/speakersPostRegistrado.php
  stages/ecommerce/during/ecommerce.php
  stages/ecommerce/post/ecommerce-registrado.php
  stages/ecommerce/post/ecommerce.php
  stages/ecommerce/pre/ecommerce-registrado.php
Labels: size/XXL

#78 DS-5133_feadback_post_deployd
  index.php
  registrado.php
  speaker-interna.php
  sponsors-registrado.php
  sponsors.php
  src/components/speakersPost.php
  src/components/speakersPostRegistrado.php
  src/img/conferences24/logos/facturante-logo.png
  stages/ecommerce/post/ecommerce.php
Labels: size/M

#81 DS-5138_fix_content_style
  src/1.0.0/css/components/hero-registration.css
Labels: size/XS
