Repository FromDoppler/emms24, pull requests merged in 2024-10, with the labels that each got.

#107 DS-5265 schedule component
  .gitignore
  admin/speakers/uploads/.gitkeep
  components/digital-trends/schedule/mobile-carousel.php
  components/digital-trends/schedule/schedule.php
  components/digital-trends/schedule/showSpeakersByDay.php
  components/digital-trends/schedule/speakers.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
Labels: size/L

#108 DS-5305 udpate paths required files
  components/digital-trends/pre/benefit-icons.php
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/companies-list.php
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/doppler-academy-banner.php
  components/digital-trends/pre/event-numbers.php
  components/digital-trends/pre/faqs.php
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/home/hello-module.php
  components/digital-trends/pre/premium-content.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/register-withoutform.php
  components/digital-trends/pre/speakers-carousel.php
  components/digital-trends/pre/users-comments.php
  components/digital-trends/schedule/mobile-carousel.php
  components/digital-trends/schedule/showSpeakersByDay.php
  components/footer.php
  components/head.php
  components/navbar-reg.php
  components/navbar-unreg.php
  components/share.php
  descarga-certificado.php
  digital-trends-registrado.php
  digital-trends.php
  ecommerce-registrado.php
  ecommerce.php
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  index.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  pages/digital-trends/pre/home-registrado.php
  pages/digital-trends/pre/home.php
  registrado.php
  speaker-interna.php
  sponsors-interna.php
  sponsors-promo.php
  sponsors-registrado.php
  sponsors.php
Labels: size/XXL

#109 DS-5306 admin schedule preview
  admin/speakers/index.php
  admin/speakers/schedule-preview.php
  src/components/cacheSettings.php
Labels: size/M

#110 DS-5306 schedule style for admin preview
  admin/speakers/add_speakers.php
  admin/speakers/edit_speakers.php
  components/digital-trends/schedule/schedule.php
  src/1.0.0/css/components/calendar.css
Labels: size/S

#111 DS-5308 schedule feedback
  components/digital-trends/schedule/schedule.php
  components/digital-trends/schedule/showSpeakersByDay.php
  pages/digital-trends/pre/digital-trends-registrado.php
  src/1.0.0/css/components/calendar.css
Labels: size/S

#113 DS-5325 add succes story in admin
  admin/speakers/add_speakers.php
  admin/speakers/edit_speakers.php
Labels: size/XS

#112 DS-5324 add success story
  components/digital-trends/schedule/mobile-carousel.php
  components/digital-trends/schedule/showSpeakersByDay.php
  src/1.0.0/css/components/calendar.css
Labels: size/M

#114 DS-5342 stripe env vars
  .docker/docker-compose.yml
  config.php
Labels: size/XS

#116 DS-5329 faq checkout
  components/digital-trends/pre/checkout/faq.php
Labels: size/M

#117 DS-5330 checkout success
  checkout-success.php
  components/digital-trends/pre/checkout/checkout-success.php
  pages/digital-trends/pre/checkout-success.php
Labels: size/L

#118 DS-5326 entry plans module
  components/digital-trends/pre/digital-trends/entry-plans.php
  pages/digital-trends/pre/digital-trends-registrado.php
  src/img/icons/icon-microphone.svg
Labels: size/L

#119 DS-5322 add video ticketing module
  components/digital-trends/pre/digital-trends/video-ticketing.php
  pages/digital-trends/pre/digital-trends-registrado.php
  src/1.0.0/css/components/central-video.css
Labels: size/M

#120 DS-5323 vip pass module
  components/digital-trends/pre/digital-trends/vip-features.php
  pages/digital-trends/pre/digital-trends-registrado.php
  src/1.0.0/css/components/features.css
Labels: size/M

#121 DS-5328 fix event name
  components/digital-trends/pre/checkout/checkout.php
  components/digital-trends/pre/faqs.php
  pages/digital-trends/pre/digital-trends.php
Labels: size/S

#122 DS-5345 marquee component
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/register-withoutform.php
  components/marquee.php
  speaker-interna.php
  sponsors-promo.php
  stages/ecommerce/during/ecommerce-registrado.php
  stages/ecommerce/during/ecommerce.php
  stages/ecommerce/post/ecommerce-registrado.php
  stages/ecommerce/post/ecommerce.php
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/XL

#123 DS-5321 add vip hero
  components/digital-trends/pre/digital-trends/hello-vip-module.php
  src/1.0.0/css/components/hero-registration.css
Labels: size/S

#124 DS-5347 checkout y checkout success spinner on mount component
  components/digital-trends/pre/checkout/checkout-success.php
  components/digital-trends/pre/checkout/checkout.php
Labels: size/L

#126 DS-5339 stripe checkout flow config
  .docker/docker-compose.yml
  config.php
  stripe/controllers/StripeCustomersController.php
  stripe/models/RegisteredDatabase.php
Labels: size/M

#127 DS-5327 vip modules logic
  components/digital-trends/pre/digital-trends/entry-plans.php
  pages/digital-trends/pre/digital-trends-registrado.php
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/js/toggleVipElements.js
Labels: size/M

#130 DS-5354 show form mobile first
  components/digital-trends/pre/register-form.php
  src/1.0.0/css/components/form.css
  src/1.0.0/css/components/hero-registration.css
Labels: size/L

#129 DS-5353 fix mobile iframe
  src/1.0.0/css/components/central-video.css
Labels: size/XS

#131 DS-5351 change entry plans
  components/digital-trends/pre/digital-trends/entry-plans.php
Labels: size/XS

#132 DS-5350 edit vip features module
  components/digital-trends/pre/digital-trends/vip-features.php
  src/1.0.0/css/components/features.css
Labels: size/M

#134 DS-5352 schedule changes
  components/digital-trends/pre/digital-trends/entry-plans.php
  components/digital-trends/schedule/schedule.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/central-video.css
Labels: size/M

#135 DS-5348 final content
  components/digital-trends/pre/doppler-academy-banner.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/schedule/schedule.php
  components/digital-trends/schedule/showSpeakersByDay.php
  components/sponsorsList.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/pages/previous-editions.css
Labels: size/L

#136 DS-5362 home feedbackdemo changes
  components/digital-trends/pre/home/hello-module.php
  src/1.0.0/css/components/event-cards.css
  src/img/card-image-ecommerce-new.png
Labels: size/M

#137 DS-5363 schedule changes
  components/digital-trends/schedule/mobile-carousel.php
  components/digital-trends/schedule/schedule.php
  components/digital-trends/schedule/showSpeakersByDay.php
  components/digital-trends/schedule/speakers.php
Labels: size/M

#138 DS-5364 vip demo changes
  components/digital-trends/pre/digital-trends/entry-plans.php
  components/digital-trends/pre/digital-trends/hello-vip-module.php
  components/digital-trends/pre/digital-trends/video-ticketing.php
  components/digital-trends/pre/digital-trends/vip-features.php
  src/1.0.0/css/components/features.css
  src/1.0.0/css/general/constants.css
Labels: size/M

#139 DS-5365 checkout feedback demo
  components/digital-trends/pre/checkout/checkout-success.php
  components/digital-trends/pre/checkout/faq.php
  components/digital-trends/schedule/showSpeakersByDay.php
  pages/digital-trends/pre/digital-trends-registrado.php
  src/1.0.0/css/components/frequent-questions.css
  src/1.0.0/css/pages/checkout.css
  src/1.0.0/js/newDate.js
  src/img/bg-section-7.png
  src/img/logos/logo-emms--gray.png
Labels: size/L

#140 DS-5339 env stripe server
  components/digital-trends/pre/checkout/checkout-success.php
Labels: size/XS

#141 hot_fix_post_deplo
  components/digital-trends/pre/checkout/faq.php
  components/digital-trends/pre/digital-trends/entry-plans.php
  components/digital-trends/pre/digital-trends/video-ticketing.php
  components/digital-trends/pre/digital-trends/vip-features.php
  components/digital-trends/schedule/schedule.php
  src/1.0.0/css/components/central-video.css
Labels: size/L

#142 DS-5367 change content
  components/digital-trends/pre/register-form.php
Labels: size/XS

#143 DS-5370 fix register withoutform flow
  pages/digital-trends/pre/digital-trends.php
Labels: size/XS

#144 DS-5369 hide sponsors list module
  components/sponsorsList.php
  sponsors-registrado.php
  sponsors.php
Labels: size/L

#146 DS-5374 add gtm with hotjar
  src/components/gtm.php
  src/components/head.php
Labels: size/M
