Repository FromDoppler/emms24, pull requests merged in 2024-08, with the labels that each got.

#86 DS-5195 components abstraction refactor
  components/digital-trends/pre/benefit-icons.php
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/companies-list.php
  components/digital-trends/pre/digital-trends/head.php
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/doppler-academy-banner.php
  components/digital-trends/pre/event-numbers.php
  components/digital-trends/pre/faqs.php
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/hellobar-vip.php
  components/digital-trends/pre/hellobar.php
  components/digital-trends/pre/home/head.php
  components/digital-trends/pre/home/hello-module.php
  components/digital-trends/pre/premium-content.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/speakers-carousel.php
  components/digital-trends/pre/users-comments.php
  components/footer.php
  components/gtm.php
  components/head.php
  components/navbar-reg.php
  components/navbar-unreg.php
  components/share.php
Labels: size/XXL

#87 DS-5177 digital trends pages home & interna
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  pages/digital-trends/pre/home-registrado.php
  pages/digital-trends/pre/home.php
Labels: size/L

#89 DS-5196 form login DT
  src/1.0.0/js/common/switchForm.js
  src/1.0.0/js/homeDigital.js
Labels: size/M

#90 DS-5176 new emms layout
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/companies-list.php
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/doppler-academy-banner.php
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/home/hello-module.php
  components/digital-trends/pre/premium-content.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/speakers-carousel.php
  components/digital-trends/pre/users-comments.php
  components/navbar-reg.php
  components/navbar-unreg.php
  pages/digital-trends/pre/digital-trends.php
  pages/digital-trends/pre/home-registrado.php
  pages/digital-trends/pre/home.php
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/css/components/doppler-academy-banner.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/grid.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/js/global.js
  src/img/card-image-digitaltrends-pre.png
  src/img/logos--white/logo-neil.png
  src/img/logos--white/logo-spotify.png
  src/img/logos--white/logo-tim-ash.png
  src/img/logos--white/logo-vedant.png
  src/img/logos--white/logo-vilma.png
  src/img/people--gradient/ana-laura-fleba-img.png
  src/img/people--gradient/diana.png
  src/img/people--gradient/guillermo.png
  src/img/people--gradient/manuel-garcia-cuerva-img.png
  src/img/people--gradient/marcos.png
  src/img/people--gradient/neil.png
  src/img/people--gradient/ricardo-tayer-img.png
  src/img/people--gradient/tim-ash.png
  src/img/people--gradient/vedant-misra.png
  src/img/people--gradient/vilma.png
  src/img/quotes/quote-yolanda.png
Labels: size/XXL

#91 DS-5198 add dt register without form
  components/digital-trends/pre/register-withoutform.php
  pages/digital-trends/pre/digital-trends.php
  src/1.0.0/js/homeDigital.js
Labels: size/L

#92 DS-5199 replace old links
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  sponsors-promo.php
  sponsors-registrado.php
  sponsors.php
Labels: size/S

#93 DS-5179 new list dt early
  config.php
Labels: size/XS

#94 DS-5200 feedback demo
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/companies-list.php
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/home/hello-module.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/register-withoutform.php
  components/digital-trends/pre/speakers-carousel.php
  components/share.php
  descarga-certificado.php
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  speaker-interna.php
  sponsors-promo.php
  sponsors.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/doppler-academy-banner.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/grid.css
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/js/homeDigital.js
  src/components/doppler-academy-banner.php
  src/img/icons/icon-check--strong-purple.svg
  src/img/logos/logo-timash.png
  stages/ecommerce/during/ecommerce.php
  stages/ecommerce/post/ecommerce.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/L

#95 DS-5182 add dt pre email
  utils/relay-templates/dt/dt-pre-template.html
Labels: size/XXL

#96 DS-5175 change_card_content
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
Labels: size/S

#97 DS-5198 fix marquee
  components/digital-trends/pre/register-withoutform.php
Labels: size/XS

#98 DS-5199 navbar detect active path
  components/navbar-reg.php
  components/navbar-unreg.php
Labels: size/L

#99 DS-5202 add new videos
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/home/head.php
  share-2024.png
  src/components/head-home.php
Labels: size/S

#100 hot fix
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/register-withoutform.php
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/js/previousEditions.js
  src/1.0.0/js/sponsors.js
  src/img/emms-dt-background.png
Labels: size/S

#101 DS-5210 dt registrado central video component
  components/digital-trends/pre/digital-trends/registrado/central-video.php
  pages/digital-trends/pre/digital-trends-registrado.php
Labels: size/S

#102 DS-5173 feedback post deploy
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/companies-list.php
  components/digital-trends/pre/digital-trends/head.php
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/home/hello-module.php
  components/digital-trends/pre/premium-content.php
  components/digital-trends/pre/speakers-carousel.php
  components/helpers/urlHelper.php
  components/share.php
  ediciones-anteriores-registrado.php
  pages/digital-trends/pre/digital-trends-registrado.php
  src/1.0.0/css/components/doppler-academy-banner.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/css/pages/sponsors.css
  src/img/people--gradient/tim-ash.png
Labels: size/M

#103 changes input form
  components/digital-trends/pre/register-form.php
  ediciones-anteriores.php
  services/register.php
  sponsors.php
  src/1.0.0/js/common/submitForm.js
  utils/DB.php
  utils/Doppler.php
  utils/SpreadSheetGoogle.php
Labels: size/L

#104 DS-5193 link to dhtrak && firebase messagin sw script
  components/head.php
Labels: size/XS

#105 DS-5215 refactor central video component
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/digital-trends/registrado/central-video.php
  pages/digital-trends/pre/digital-trends-registrado.php
Labels: size/M
