Repository FromDoppler/emms24, pull requests merged in 2024-07, with the labels that each got.

#82 DS-5171 docker update
  .docker/docker-compose.yml
  .gitignore
Labels: size/S

#83 DS-5172 dt index
  index.php
Labels: size/XXL

#84 DS-5175 previous editions block
  ediciones-anteriores.php
  src/1.0.0/css/pages/previous-editions.css
  src/img/editions/edicion2023-ecommerce-xl.png
Labels: size/L

#85 DS-5175_fix_previous_editions
  ediciones-anteriores-registrado.php
  src/1.0.0/css/pages/previous-editions.css
Labels: size/S
