Repository FromDoppler/emms24, pull requests merged in 2024-03, with the labels that each got.

#17 DS-5048_new_date_script
  src/1.0.0/css/scripts/common.css
  src/1.0.0/css/styles.css
  src/1.0.0/js/common/version.js
  src/1.0.0/js/newDate.js
  src/1.0.0/js/vendors/moment-timezone-data.min.js
  src/1.0.0/js/vendors/moment.min.js
  src/components/footer.php
Labels: size/L

#25 DS-5063 upate subscription list
  services/register.php
Labels: size/XS

#28 DS-5041 docker network
  .docker/docker-compose.yml
Labels: size/S

#29 DS-5041 create customer endpoint
  stripe/controllers/StripeCustomersController.php
  stripe/createCustomer.php
  stripe/models/StripeCustomersDatabase.php
Labels: size/L

#30 DS-5020-Previous-editions-design-update-v2
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  src/1.0.0/css/pages/previous-editions.css
Labels: size/XS

#31 DS-5070-Update-home-cards-design
  index.php
  registrado.php
  src/1.0.0/css/components/event-cards.css
  src/img/card-image-digitaltrends-24.png
  src/img/card-image-digitaltrends.png
  src/img/card-image-ecommerce-24.png
  src/img/card-image-ecommerce.png
Labels: size/L

#33 DS-5068 registered model & add attr stripe
  stripe/controllers/StripeCustomersController.php
  stripe/createCustomer.php
  stripe/models/RegisteredDatabase.php
  stripe/models/StripeCustomersDatabase.php
Labels: size/L

#34 DS-5074_ecommerce_current_register_flow
  config.php
  ecommerce-registrado.php
  ecommerce.php
  services/getRegisteredByEmail.php
  services/register.php
  src/1.0.0/js/common/formsValidators.js
  src/1.0.0/js/common/submitForm.js
  src/1.0.0/js/enums/eventsType.enum.js
  src/1.0.0/js/homeDigital.js
  src/1.0.0/js/homeEcommerce.js
  src/1.0.0/js/popUp.js
  src/1.0.0/js/previousEditions.js
  src/1.0.0/js/speakersInterna.js
  src/1.0.0/js/sponsors.js
  src/1.0.0/js/user.js
  src/components/cacheSettings.php
  utils/Relay.php
  utils/newDB.php
  utils/stripe/StripeCustomersController.php
  utils/stripe/StripeCustomersModel.php
Labels: size/L

#37 email-ecommerce-vip
  utils/relay-templates/ecommerce/ecommerce-vip-template.html
Labels: size/L

#38 ecommerce-layout-details
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/js/calendarBio.js
Labels: size/S
