Repository FromDoppler/emms24, pull requests merged in 2024-12, with the labels that each got.

#216 DS-5453 change button
  components/SpeakerCardComponent/DescriptionButton.php
Labels: size/L

#217 DS-5455 enable interna debate
  components/SpeakerCardComponent/DescriptionButton.php
Labels: size/XS

#218 DS-5456 capsula sponsor wextion
  sponsors-registrado.php
  sponsors.php
  src/img/conferences24/logos/wextion-exclusive-logo.png
  src/img/conferences24/portada-wextion-min.png
Labels: size/S

#219 DS-5460 button post content
  components/digital-trends/post/register-form.php
Labels: size/XS
