Repository FromDoppler/emms24, pull requests merged in 2024-02, with the labels that each got.

#3 DS-5030_new_spread
  config.php
Labels: size/XS

#4 DS-5032-Earlybirds-files-v2
  ecommerce.php
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  index.php
  registrado.php
  sponsors-registrado.php
  sponsors.php
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
  wix/readme
  wix/v1/api/controllers/SubscriberController.php
  wix/v1/api/controllers/WixContactController.php
  wix/v1/api/find_contact_by_email.php
  wix/v1/api/models/SubscriberDatabase.php
  wix/v1/api/models/SubscriberDopplerList.php
  wix/v1/api/models/SubscriberWix.php
  wix/v1/api/models/WixContactsDatabase.php
  wix/v1/api/save_subscriber_data.php
  wix/v1/api/update_contact_name.php
  wix/v1/api/utils/Logger.php
  wix/v1/api/utils/SpreadSheetGoogle.php
  wix/v1/api/utils/WixApiClient.php
  wix/v1/api/utils/email-doble-optin.html
  wix/v1/api/utils/getCurrentPhase.php
  wix/v1/api/utils/sendEmail.php
  wix/v1/api/utils/toHex.php
Labels: size/XXL

#5 DS-5039-Earlybirds-layout
  ecommerce-registrado.php
  index.php
  registrado.php
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/event-numbers.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/js/dateCounter.js
  src/components/speakers.php
  src/img/back-hero--dk-24.png
  src/img/back-hero--dk.png
  src/img/back-hero--mb-24.png
  src/img/back-hero--mb.png
  src/img/back-hero-ecommerce.png
  src/img/card-image-digitaltrends-24.png
  src/img/card-image-digitaltrends.png
  src/img/card-image-ecommerce-24.png
  src/img/card-image-ecommerce.png
  src/img/download--locked-24.png
  src/img/icons/icon-eventnumber-1.svg
  src/img/icons/icon-eventnumber-2.svg
  src/img/icons/icon-eventnumber-3.svg
  src/img/icons/icon-eventnumber-4.svg
  src/img/icons/icon-ticket-fill.svg
  stages/ecommerce/pre/ecommerce.php
Labels: size/XXL

#6 DS-5038_integrate_form_flow
  config.php
  src/1.0.0/js/common/user.js
  src/1.0.0/js/homeEcommerce.js
  src/1.0.0/js/user.js
  stages/ecommerce/pre/ecommerce.php
Labels: size/L

#7 DS-5039-Earlybirds-layout-v2
  src/1.0.0/css/components/basic-section.css
  src/1.0.0/css/components/date-counter.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/css/styles.css
  src/img/bg-section-1.png
  src/img/icons/icon-calendar.svg
  src/img/icons/icon-two-dots.svg
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/L

#9 DS-5035_fix_file_name
  ecommerce-registrado.php
  ecommerce.php
  src/1.0.0/js/homeDigital.js
  src/1.0.0/js/homeEcommerce.js
  src/1.0.0/js/popUp.js
  src/1.0.0/js/previousEditions.js
  src/1.0.0/js/speakersInterna.js
  src/1.0.0/js/sponsors.js
  utils/Relay.php
  utils/SubscriptionErrors.php
Labels: size/M

#10 DS-5039-Earlybirds-layout-v3
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  index.php
  registrado.php
  sponsors-interna.php
  sponsors-registrado.php
  sponsors.php
  src/1.0.0/css/components/doppler-academy-banner.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/internal-sponsors.css
  src/1.0.0/css/pages/previous-editions.css
  src/1.0.0/css/pages/sponsors.css
  src/1.0.0/js/commonAnimations.js
  src/components/doppler-academy-banner.php
  src/img/academy-podcasts.png
  src/img/academy-webinars.png
  src/img/back-hero-sponsors--dk.png
  src/img/bg-section-2.png
  src/img/rectangle-format-mobile.svg
  src/img/rectangle-format.svg
  src/img/team-doppler.png
Labels: size/XL

#11 change name adm & prefix
  adm24/getAllRegistersEMMS.php
  adm24/index.php
  adm24/server/config/config.php
  adm24/server/modules/doppler_list_errors/getDopplerListErrors.php
  adm24/server/modules/settings/getPhase.php
  adm24/server/modules/settings/sendRefresh.php
  adm24/server/modules/settings/setPhase.php
  adm24/server/modules/settings/setTransmission.php
  adm24/server/modules/sponsors/addSponsor.php
  adm24/server/modules/sponsors/getSponsors.php
  adm24/server/modules/sponsors/removeSponsor.php
  adm24/server/modules/sponsors/uploads/20230320T160011181Z729033.jfif
  adm24/server/modules/sponsors/uploads/20230322T130241359Z607858.jpg
  adm24/server/modules/sponsors/uploads/20230331T125941990Z380764.png
  adm24/server/modules/sponsors/uploads/20230331T131302920Z736506.png
  adm24/server/modules/sponsors/uploads/empty
  adm24/server/modules/sponsors/uploads/juan-lombana-site.png
  adm24/server/modules/sponsors/uploads/mercatitlan-speaker.png
  adm24/src/main.js
  adm24/src/modules/doppler_list_errors/components/errors_list/errorsList.html
  adm24/src/modules/doppler_list_errors/components/errors_list/errorsList.js
  adm24/src/modules/doppler_list_errors/components/errors_list/errrorsRows.js
  adm24/src/modules/doppler_list_errors/components/errors_list/getErrors.js
  adm24/src/modules/navbar/navbar.html
  adm24/src/modules/navbar/navbar.js
  adm24/src/modules/settings/phases/phases-list.html
  adm24/src/modules/settings/phases/services/getPhase.js
  adm24/src/modules/settings/phases/services/sendRefresh.js
  adm24/src/modules/settings/phases/services/setPhase.js
  adm24/src/modules/settings/phases/showPhasesList.js
  adm24/src/modules/settings/settings.html
  adm24/src/modules/settings/settings.js
  adm24/src/modules/sponsors/components/sponsor-form/hiddenFieldList.js
  adm24/src/modules/sponsors/components/sponsor-form/sponsor-form.html
  adm24/src/modules/sponsors/components/sponsor-form/sponsorForm.js
  adm24/src/modules/sponsors/components/sponsors-list/getSponsors.js
  adm24/src/modules/sponsors/components/sponsors-list/sponsors-list.html
  adm24/src/modules/sponsors/components/sponsors-list/sponsorsList.js
  adm24/src/modules/sponsors/components/sponsors-list/sponsorsRows.js
  adm24/src/modules/sponsors/types/sponsorTypes.js
  adm24/src/modules/statistics/statistics.html
  adm24/src/modules/statistics/statistics.js
  admin/settings.php
  admin/speakers/index.php
  src/1.0.0/js/mediaPartners.js
Labels: size/S

#12 DS-5044-Add-content
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  index.php
  registrado.php
  sponsors-registrado.php
  sponsors.php
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/css/components/doppler-academy-banner.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/grid.css
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/previous-editions.css
  src/1.0.0/js/commonAnimations.js
  src/components/doppler-academy-banner.php
  src/components/footer.php
  src/img/academy-certificaciones.png
  src/img/academy-doppler-demo.png
  src/img/logos/logo-ana-ivars.png
  src/img/logos/logo-canva.png
  src/img/logos/logo-ecommerce-efectivo.png
  src/img/logos/logo-flat.png
  src/img/logos/logo-go-cuotas.png
  src/img/logos/logo-isocial.png
  src/img/logos/logo-mercatitlan.png
  src/img/logos/logo-tiipe.png
  src/img/logos/logo-tramontina.png
  src/img/logos/logo-unilever.png
  src/img/logos/logo-youtube.png
  src/img/people/speaker-alicia-macias-hernandez.png
  src/img/people/speaker-alvaro-pena-luna.png
  src/img/people/speaker-ana-ivars.png
  src/img/people/speaker-ana-laura-fleba.png
  src/img/people/speaker-ana-victoria-odonel.png
  src/img/people/speaker-diana-ramirez-2.png
  src/img/people/speaker-diego-dagnino.png
  src/img/people/speaker-emiliano-canova.png
  src/img/people/speaker-federico-munoz-villavicencio.png
  src/img/people/speaker-federico-osorio.png
  src/img/people/speaker-fernando-dacunto.png
  src/img/people/speaker-juan-lombana.png
  src/img/people/speaker-manuel-garcia-cuerva.png
  src/img/people/speaker-ricardo-tayar.png
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/XL

#13 DS-5047_fix_ecommerce_phase
  ecommerce-registrado.php
  ecommerce.php
  sponsors-interna.php
  sponsors-registrado.php
  sponsors.php
  src/components/cacheSettings.php
  stages/ecommerce/pre/ecommerce-registrado.php
Labels: size/S

#15 DS-5033-Previous-editions
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  src/img/editions/emms2020.png
  src/img/editions/emms2021.png
  src/img/editions/emms2022.png
  src/img/editions/emms2023-dt.png
  src/img/editions/emms2023-ecommerce.png
Labels: size/M

#16 DS-5033-Previous-edition-v2
  src/1.0.0/css/pages/previous-editions.css
Labels: size/XS

#20 DS-5053-Pre-deploy-modifications
  index.php
  registrado.php
  sponsors.php
  src/1.0.0/js/dateCounter.js
  src/components/head-home.php
  stages/ecommerce/pre/ecommerce-registrado.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/M

#21 DS-5056-Post-deploy-modifications
  src/1.0.0/css/components/event-numbers.css
  stages/ecommerce/pre/ecommerce.php
Labels: size/XS

#23 DS-5059_fix_spread
  services/register.php
  stages/ecommerce/pre/ecommerce.php
Labels: size/XS
